spring.application.name=habittracker-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/habittracker_db
spring.datasource.username=habittracker_user
spring.datasource.password=habittracker_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=bXktdmVyeS1sb25nLXN1cGVyLXNlY3VyZS1oYWJpdHRyYWNrZXItand0LXNlY3JldC1rZXktMTIzNDU2Nzg5MA==
app.jwt.expiration-ms=86400000

management.endpoints.web.exposure.include=health,info